<!doctype html>
<html lang="en" style="display:block;min-width:1070px;">
<head>
<meta name="distribution" content="global" />
<meta name="robots" content="follow, all" />
 <meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
<meta name="google-site-verification" content="GTY8q3lGYJyB0uT2U_vjhGkaQdrK17O9i9M5MPMBBa0" />
<meta name="norton-safeweb-site-verification" content="7jyvwknvdv-yfjlzt3cdz5l34h9x7f-83bdh3x3k8mjo4bci55-m3zptqbcd9hef8-62ff6hrcor8prt-i1fw6lej5kw6wovojjadjkw228gbvsi8kc6hb8n1lb270tm" />
<meta name="viewport" content="width=1070">
	
<meta name="googlebot" content="noindex,follow"> 

<!-- Escape from Frames -->
<script type="text/javascript">if(self==top){document.documentElement.style.display="block"}else{top.location=self.location}</script>
<link href="https://fonts.googleapis.com/css?family=Droid+Sans" rel="stylesheet">
<link rel="stylesheet" href="https://transcriptdaily.com/wp-content/themes/newsalambre/style.css?v=3" type="text/css" media="screen" />
<link href="https://transcriptdaily.com/feed" rel="alternate" title="Transcript Daily RSS Feed" type="application/rss+xml" />
<link href="https://transcriptdaily.com/feed/atom" rel="alternate" title="Transcript Daily Atom Feed" type="application/atom+xml" />
<link href="https://transcriptdaily.com/xmlrpc.php" rel="pingback" />
<link rel='dns-prefetch' href='//s.w.org' />
<link rel="alternate" type="application/rss+xml" title="Transcript Daily &raquo; Search Results for &#8220;ADP&#8221; Feed" href="https://transcriptdaily.com/search/ADP/feed/rss2/" />
<link rel='stylesheet' id='wp-block-library-css'  href='https://transcriptdaily.com/wp-includes/css/dist/block-library/style.min.css?ver=5.4.2' type='text/css' media='all' />
<link rel='https://api.w.org/' href='https://transcriptdaily.com/wp-json/' />
<link rel="EditURI" type="application/rsd+xml" title="RSD" href="https://transcriptdaily.com/xmlrpc.php?rsd" />
<link rel="wlwmanifest" type="application/wlwmanifest+xml" href="https://transcriptdaily.com/wp-includes/wlwmanifest.xml" /> 
<meta name="generator" content="WordPress 5.4.2" />
<link rel="icon" href="https://transcriptdaily.com/wp-content/uploads/2017/04/Transcript-Daily-Iconpng-06.png" sizes="32x32" />
<link rel="icon" href="https://transcriptdaily.com/wp-content/uploads/2017/04/Transcript-Daily-Iconpng-06.png" sizes="192x192" />
<link rel="apple-touch-icon" href="https://transcriptdaily.com/wp-content/uploads/2017/04/Transcript-Daily-Iconpng-06.png" />
<meta name="msapplication-TileImage" content="https://transcriptdaily.com/wp-content/uploads/2017/04/Transcript-Daily-Iconpng-06.png" />

<!-- Start Meta Data -->
<title>Grandfield &#038; Dodd LLC Sells 108 Shares of Automatic Data Processing (NASDAQ:ADP) - Transcript Daily</title>

<!-- End Meta Data -->
	
	
<script type='text/javascript'>var PopupAdChannel=''; </script>
  <link rel="manifest" href="/manifest.json">
  <script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js"></script>
  <script>
  	function registerUserChange(action) {
		OneSignal.getUserId( function(userId) {
			OneSignalIdString = userId;
			var Domain = 'transcriptdaily.com';
			var url = "https://www.marketbeat.com/scripts/OneSignalTracking.ashx?OneSignalID=" + OneSignalIdString + "&domain=" + Domain + "&action=" + action;
			var xhr = new XMLHttpRequest();
			xhr.open('GET', url);
			xhr.onload = function () {
				if (xhr.status !== 200) {
					console.log('GET failed.  Returned status of ' + xhr.status);
				}
			};
			xhr.send();
		});
	}
    var OneSignal = window.OneSignal || [];
    OneSignal.push(["init", {
      appId: "881bfa77-26cb-4cd6-9aa9-572b33abb76a",
      safari_web_id: 'web.onesignal.auto.1d2463f6-17a6-4c7e-80c3-735ae8ddc977', 
      autoRegister: false,
      autoResubscribe: true,		
      notifyButton: {
        enable: false /* Set to false to hide */
      },
 welcomeNotification: {
        "title": "Join Wall Street's Brightest Minds.",
        "message": "Receive research in your inbox from top analysts, before the market opens. Click here to learn how.",
         "url": "https://www.marketbeat.com/subscribe/subscribe.aspx?ReferralType=OneSignalThankYou&ProductCode=1997t"
    }
    },
		OneSignal.once('subscriptionChange', function (isSubscribed) {
			if(isSubscribed) {
				registerUserChange("subscribe");
			}
			else {
				registerUserChange("unsubscribe");
			}
			
		  })
	]);
	if((navigator.userAgent.toLowerCase().indexOf('firefox') > -1)||((navigator.userAgent.toLowerCase().indexOf('safari') > -1)&&(!(navigator.userAgent.toLowerCase().indexOf('chrome') > -1)))){
		OneSignal.showSlidedownPrompt();
	} else {
		OneSignal.showNativePrompt();		
	}
  </script>
<script type="text/javascript">var vbnfgha = '211626'; var ertdfga = '13739-bup-ac'; var qhyuioa = '53938'; var AdClientID = qhyuioa + vbnfgha + ertdfga; AdClientID = AdClientID.split("").reverse().join("");</script>

<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({
          google_ad_client: AdClientID,
          enable_page_level_ads: true
     });
</script>
<!-- Start IMS -->
<script type="text/javascript">
		var apntag = apntag || {};
		apntag.anq = apntag.anq || [];
		(function() {
			var d = document, e = d.createElement('script'), p = d.getElementsByTagName('head')[0];
			e.type = 'text/javascript';  e.async = true;
			e.src = '//acdn.adnxs.com/ast/ast.js';
			p.insertBefore(e, p.firstChild);
		})();

		
		apntag.anq.push(function() {
			apntag.setPageOpts({
				member: 6989
			});
		});

		apntag.anq.push(function() {

      		apntag.defineTag({
				tagId: 13207769,
				sizes: [[300,250],[300,600],[300,1050]],
				keywords: {'position': ['RightRail_1']},
				targetId: 'TranscriptDaily_ROS_RightRail_1'
			});
					});

		apntag.anq.push(function() {
			apntag.loadTags();
		});
		</script>
	
<script type="text/javascript">
(function() {
window.advBidxc = window.advBidxc || {};
window.advBidxc.startTime = new Date().getTime();
function loadScript(tagSrc) {
var scriptTag = document.createElement('script'),
placeTag = document.getElementsByTagName("script")[0];
scriptTag.type = 'text/javascript';
scriptTag.async = true;
scriptTag.src = tagSrc;
placeTag.parentNode.insertBefore(scriptTag, placeTag);
}
var mnSrc = '//hbx.media.net/bidexchange.js?cid=8CU2C156D&version=5.1' + '&dn=' +
window.location.hostname;
loadScript(mnSrc);
})();
</script>
<!-- End IMS --> 
	

</head>
<body>
<div id="wrap">

<!-- Start MarketBeat Modern Popup -->
<link rel="stylesheet" type="text/css" media="all" href="https://www.marketbeat.com/scripts/modal/modernpopup.css?v=11"/>
<script type="text/javascript" src="https://www.marketbeat.com/scripts/modal/modernpopup.js?v=52"></script>

	<script type="text/javascript">LoadPopupRatings('ModernNonMarketsPopup-Transcript Daily', 'transcriptdaily.com');</script>
<!-- End MarketBeat Modern Popup -->
	
<header>
	<div id="top-bar">
		<div class="width-limiter">
				<!-- top nav bar -->
				<nav class="navigation"><ul id="menu-top-menu" class="menu"><li id="menu-item-81" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-81"><a href="https://transcriptdaily.com">Home</a></li>
<li id="menu-item-83" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-83"><a href="https://transcriptdaily.com/privacy-policy">Privacy Policy</a></li>
<li id="menu-item-84" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-84"><a href="https://transcriptdaily.com/about-contact">About/Contact</a></li>
</ul></nav>				<form id="searchform" action="https://transcriptdaily.com/" method="get">
					<div id="search">
						<input id="s" class="searchinput" name="s" onclick="this.value='';" type="text" />
						<input class="searchsubmit" type="submit" value="SEARCH" />
					</div>
				</form><!-- end: searchform -->
		</div><!-- end: width-limiter in top-bar -->
	</div><!-- end: top-bar -->
	<div class="width-limiter add-padding"><!-- start: width-limiter with logo and space for alternate header unit -->
		<a class="logo-link" href="https://transcriptdaily.com"><img id="logo" src="/wp-content/uploads/2017/04/Transcript-Daily-Logo-04.png" alt="Transcript Daily logo"></a>

<!-- Begin Header Unit -->
<div id="AlternateHeaderUnit">
		
		<iframe src="https://marketbeat.com/scripts/HeaderAdNewsSites.ashx" width="728" height="90" frameborder="no" scrolling="no"></iframe>
			</div> 

<!-- End Header Unit-->
	</div> <!-- end: width-limiter with logo and space for alternate header unit -->
	<div id="menu">
		<div class="width-limiter" id="nav-main">
			<!-- start main category menu -->
			<nav class="navigation"><ul id="menu-categories-for-menus" class="menu"><li id="menu-item-79" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-79"><a href="https://transcriptdaily.com/headlines">Headlines</a></li>
<li id="menu-item-75" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-75"><a href="https://transcriptdaily.com/business">Business</a></li>
<li id="menu-item-77" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-77"><a href="https://transcriptdaily.com/markets">Markets</a></li>
<li id="menu-item-80" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-80"><a href="https://transcriptdaily.com/politics">Politics</a></li>
<li id="menu-item-78" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-78"><a href="https://transcriptdaily.com/technology">Technology</a></li>
<li id="menu-item-76" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-76"><a href="https://transcriptdaily.com/health">Health</a></li>
</ul></nav>		</div> <!-- end: width-limiter for menu -->
	</div> <!-- end: menu -->
</header> <!-- end: header -->
	<div class="width-limiter main-content">
		
<main>
						<h1 class="archive-category"><a href="https://transcriptdaily.com">Home</a> &raquo; Search Results</h1>
								<section class="archive">
					<a href="https://transcriptdaily.com/2020/07/26/grandfield-dodd-llc-sells-108-shares-of-automatic-data-processing-nasdaqadp.html" rel="bookmark" title="Grandfield &#038; Dodd LLC Sells 108 Shares of Automatic Data Processing (NASDAQ:ADP)">
					<img src="https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/automatic-data-processing-logo.png&amp;h=100&amp;w=100&amp;zc=1" alt="Grandfield &#038; Dodd LLC Sells 108 Shares of Automatic Data Processing (NASDAQ:ADP)" />
					<h2>Grandfield &#038; Dodd LLC Sells 108 Shares of Automatic Data Processing (NASDAQ:ADP)</h2>
					<p class="postmeta">
						Posted by <a href="https://transcriptdaily.com/author/lasteadman" title="Posts by Lauren Steadman" rel="author">Lauren Steadman</a> on Jul 26th, 2020 // <span class="comments-link">Comments off</span>					</p><!--end .postmeta-->
					<div class="entry">
						Grandfield &#038; Dodd LLC trimmed its position in  Automatic Data Processing (NASDAQ:ADP) by 1.6% in the 2nd quarter, according to the company in its most recent filing with the Securities and Exchange Commission (SEC). The firm owned...&nbsp;<a href='https://transcriptdaily.com/2020/07/26/grandfield-dodd-llc-sells-108-shares-of-automatic-data-processing-nasdaqadp.html'></a>					</div></a>
				</section> <!-- end archive -->
								<section class="archive">
					<a href="https://transcriptdaily.com/2020/07/25/adaptive-biotechnologies-corporation-nasdaqadpt-director-sells-80000000-00-in-stock.html" rel="bookmark" title="Adaptive Biotechnologies Corporation (NASDAQ:ADPT) Director Sells $80,000,000.00 in Stock">
					<img src="https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/generic-stocks.jpg&amp;h=100&amp;w=100&amp;zc=1" alt="Adaptive Biotechnologies Corporation (NASDAQ:ADPT) Director Sells $80,000,000.00 in Stock" />
					<h2>Adaptive Biotechnologies Corporation (NASDAQ:ADPT) Director Sells $80,000,000.00 in Stock</h2>
					<p class="postmeta">
						Posted by <a href="https://transcriptdaily.com/author/jaquigley" title="Posts by James Quigley" rel="author">James Quigley</a> on Jul 25th, 2020 // <span class="comments-link">Comments off</span>					</p><!--end .postmeta-->
					<div class="entry">
						Adaptive Biotechnologies Corporation (NASDAQ:ADPT) Director David E. Goel sold 2,000,000 shares of the company&#8217;s stock in a transaction on Monday, July 20th. The shares were sold at an average price of $40.00, for a total transaction...&nbsp;<a href='https://transcriptdaily.com/2020/07/25/adaptive-biotechnologies-corporation-nasdaqadpt-director-sells-80000000-00-in-stock.html'></a>					</div></a>
				</section> <!-- end archive -->
								<section class="archive">
					<a href="https://transcriptdaily.com/2020/07/24/tarbox-family-office-inc-boosts-stake-in-automatic-data-processing-nasdaqadp.html" rel="bookmark" title="Tarbox Family Office Inc. Boosts Stake in Automatic Data Processing (NASDAQ:ADP)">
					<img src="https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/automatic-data-processing-logo.png&amp;h=100&amp;w=100&amp;zc=1" alt="Tarbox Family Office Inc. Boosts Stake in Automatic Data Processing (NASDAQ:ADP)" />
					<h2>Tarbox Family Office Inc. Boosts Stake in Automatic Data Processing (NASDAQ:ADP)</h2>
					<p class="postmeta">
						Posted by <a href="https://transcriptdaily.com/author/liflegge" title="Posts by Linda Flegge" rel="author">Linda Flegge</a> on Jul 24th, 2020 // <span class="comments-link">Comments off</span>					</p><!--end .postmeta-->
					<div class="entry">
						Tarbox Family Office Inc. grew its stake in  Automatic Data Processing (NASDAQ:ADP) by 86.3% in the second quarter, according to the company in its most recent Form 13F filing with the Securities and Exchange Commission. The fund owned...&nbsp;<a href='https://transcriptdaily.com/2020/07/24/tarbox-family-office-inc-boosts-stake-in-automatic-data-processing-nasdaqadp.html'></a>					</div></a>
				</section> <!-- end archive -->
								<section class="archive">
					<a href="https://transcriptdaily.com/2020/07/24/adaptive-biotechnologies-corporation-nasdaqadpt-insider-sells-16680-00-in-stock.html" rel="bookmark" title="Adaptive Biotechnologies Corporation (NASDAQ:ADPT) Insider Sells $16,680.00 in Stock">
					<img src="https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/generic-stocks.jpg&amp;h=100&amp;w=100&amp;zc=1" alt="Adaptive Biotechnologies Corporation (NASDAQ:ADPT) Insider Sells $16,680.00 in Stock" />
					<h2>Adaptive Biotechnologies Corporation (NASDAQ:ADPT) Insider Sells $16,680.00 in Stock</h2>
					<p class="postmeta">
						Posted by <a href="https://transcriptdaily.com/author/lasteadman" title="Posts by Lauren Steadman" rel="author">Lauren Steadman</a> on Jul 24th, 2020 // <span class="comments-link">Comments off</span>					</p><!--end .postmeta-->
					<div class="entry">
						Adaptive Biotechnologies Corporation (NASDAQ:ADPT) insider Sharon Benzeno sold 417 shares of the firm&#8217;s stock in a transaction that occurred on Monday, July 20th. The stock was sold at an average price of $40.00, for a total...&nbsp;<a href='https://transcriptdaily.com/2020/07/24/adaptive-biotechnologies-corporation-nasdaqadpt-insider-sells-16680-00-in-stock.html'></a>					</div></a>
				</section> <!-- end archive -->
								<section class="archive">
					<a href="https://transcriptdaily.com/2020/07/23/1105-shares-in-automatic-data-processing-nasdaqadp-purchased-by-cerebellum-gp-llc.html" rel="bookmark" title="1,105 Shares in Automatic Data Processing (NASDAQ:ADP) Purchased by Cerebellum GP LLC">
					<img src="https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/automatic-data-processing-logo.png&amp;h=100&amp;w=100&amp;zc=1" alt="1,105 Shares in Automatic Data Processing (NASDAQ:ADP) Purchased by Cerebellum GP LLC" />
					<h2>1,105 Shares in Automatic Data Processing (NASDAQ:ADP) Purchased by Cerebellum GP LLC</h2>
					<p class="postmeta">
						Posted by <a href="https://transcriptdaily.com/author/cawalker" title="Posts by Casey Walker" rel="author">Casey Walker</a> on Jul 23rd, 2020 // <span class="comments-link">Comments off</span>					</p><!--end .postmeta-->
					<div class="entry">
						Cerebellum GP LLC acquired a new position in  Automatic Data Processing (NASDAQ:ADP) in the 2nd quarter, according to the company in its most recent disclosure with the Securities and Exchange Commission (SEC). The institutional investor...&nbsp;<a href='https://transcriptdaily.com/2020/07/23/1105-shares-in-automatic-data-processing-nasdaqadp-purchased-by-cerebellum-gp-llc.html'></a>					</div></a>
				</section> <!-- end archive -->
								<section class="archive">
					<a href="https://transcriptdaily.com/2020/07/23/comparing-halozyme-therapeutics-nasdaqhalo-and-adaptive-biotechnologies-nasdaqadpt.html" rel="bookmark" title="Comparing Halozyme Therapeutics (NASDAQ:HALO) and Adaptive Biotechnologies (NASDAQ:ADPT)">
					<img src="https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/generic-stocks.jpg&amp;h=100&amp;w=100&amp;zc=1" alt="Comparing Halozyme Therapeutics (NASDAQ:HALO) and Adaptive Biotechnologies (NASDAQ:ADPT)" />
					<h2>Comparing Halozyme Therapeutics (NASDAQ:HALO) and Adaptive Biotechnologies (NASDAQ:ADPT)</h2>
					<p class="postmeta">
						Posted by <a href="https://transcriptdaily.com/author/cawalker" title="Posts by Casey Walker" rel="author">Casey Walker</a> on Jul 23rd, 2020 // <span class="comments-link">Comments off</span>					</p><!--end .postmeta-->
					<div class="entry">
						Halozyme Therapeutics (NASDAQ:HALO) and Adaptive Biotechnologies (NASDAQ:ADPT) are both mid-cap medical companies, but which is the better investment? We will compare the two companies based on the strength of their valuation, institutional...&nbsp;<a href='https://transcriptdaily.com/2020/07/23/comparing-halozyme-therapeutics-nasdaqhalo-and-adaptive-biotechnologies-nasdaqadpt.html'></a>					</div></a>
				</section> <!-- end archive -->
								<section class="archive">
					<a href="https://transcriptdaily.com/2020/07/22/altfest-l-j-co-inc-buys-new-shares-in-automatic-data-processing-nasdaqadp.html" rel="bookmark" title="Altfest L J &#038; Co. Inc. Buys New Shares in Automatic Data Processing (NASDAQ:ADP)">
					<img src="https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/automatic-data-processing-logo.png&amp;h=100&amp;w=100&amp;zc=1" alt="Altfest L J &#038; Co. Inc. Buys New Shares in Automatic Data Processing (NASDAQ:ADP)" />
					<h2>Altfest L J &#038; Co. Inc. Buys New Shares in Automatic Data Processing (NASDAQ:ADP)</h2>
					<p class="postmeta">
						Posted by <a href="https://transcriptdaily.com/author/cawalker" title="Posts by Casey Walker" rel="author">Casey Walker</a> on Jul 22nd, 2020 // <span class="comments-link">Comments off</span>					</p><!--end .postmeta-->
					<div class="entry">
						Altfest L J &#038; Co. Inc. purchased a new stake in shares of  Automatic Data Processing (NASDAQ:ADP) during the second quarter, according to the company in its most recent 13F filing with the Securities &amp; Exchange Commission....&nbsp;<a href='https://transcriptdaily.com/2020/07/22/altfest-l-j-co-inc-buys-new-shares-in-automatic-data-processing-nasdaqadp.html'></a>					</div></a>
				</section> <!-- end archive -->
								<section class="archive">
					<a href="https://transcriptdaily.com/2020/07/22/francis-lo-sells-2000-shares-of-adaptive-biotechnologies-corporation-nasdaqadpt-stock.html" rel="bookmark" title="Francis Lo Sells 2,000 Shares of Adaptive Biotechnologies Corporation (NASDAQ:ADPT) Stock">
					<img src="https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/generic-stocks.jpg&amp;h=100&amp;w=100&amp;zc=1" alt="Francis Lo Sells 2,000 Shares of Adaptive Biotechnologies Corporation (NASDAQ:ADPT) Stock" />
					<h2>Francis Lo Sells 2,000 Shares of Adaptive Biotechnologies Corporation (NASDAQ:ADPT) Stock</h2>
					<p class="postmeta">
						Posted by <a href="https://transcriptdaily.com/author/jaquigley" title="Posts by James Quigley" rel="author">James Quigley</a> on Jul 22nd, 2020 // <span class="comments-link">Comments off</span>					</p><!--end .postmeta-->
					<div class="entry">
						Adaptive Biotechnologies Corporation (NASDAQ:ADPT) insider Francis Lo sold 2,000 shares of the firm&#8217;s stock in a transaction dated Wednesday, July 15th. The shares were sold at an average price of $43.86, for a total value of...&nbsp;<a href='https://transcriptdaily.com/2020/07/22/francis-lo-sells-2000-shares-of-adaptive-biotechnologies-corporation-nasdaqadpt-stock.html'></a>					</div></a>
				</section> <!-- end archive -->
								<section class="archive">
					<a href="https://transcriptdaily.com/2020/07/21/exeter-financial-llc-has-1-81-million-holdings-in-automatic-data-processing-nasdaqadp.html" rel="bookmark" title="Exeter Financial LLC Has $1.81 Million Holdings in Automatic Data Processing (NASDAQ:ADP)">
					<img src="https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/automatic-data-processing-logo.png&amp;h=100&amp;w=100&amp;zc=1" alt="Exeter Financial LLC Has $1.81 Million Holdings in Automatic Data Processing (NASDAQ:ADP)" />
					<h2>Exeter Financial LLC Has $1.81 Million Holdings in Automatic Data Processing (NASDAQ:ADP)</h2>
					<p class="postmeta">
						Posted by <a href="https://transcriptdaily.com/author/jocasey" title="Posts by Joseph Casey" rel="author">Joseph Casey</a> on Jul 21st, 2020 // <span class="comments-link">Comments off</span>					</p><!--end .postmeta-->
					<div class="entry">
						Exeter Financial LLC trimmed its holdings in  Automatic Data Processing (NASDAQ:ADP) by 2.7% in the second quarter, according to the company in its most recent Form 13F filing with the Securities &amp; Exchange Commission. The fund...&nbsp;<a href='https://transcriptdaily.com/2020/07/21/exeter-financial-llc-has-1-81-million-holdings-in-automatic-data-processing-nasdaqadp.html'></a>					</div></a>
				</section> <!-- end archive -->
								<section class="archive">
					<a href="https://transcriptdaily.com/2020/07/20/adaptive-biotechnologies-nasdaqadpt-downgraded-by-zacks-investment-research.html" rel="bookmark" title="Adaptive Biotechnologies (NASDAQ:ADPT) Downgraded by Zacks Investment Research">
					<img src="https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/generic-stocks.jpg&amp;h=100&amp;w=100&amp;zc=1" alt="Adaptive Biotechnologies (NASDAQ:ADPT) Downgraded by Zacks Investment Research" />
					<h2>Adaptive Biotechnologies (NASDAQ:ADPT) Downgraded by Zacks Investment Research</h2>
					<p class="postmeta">
						Posted by <a href="https://transcriptdaily.com/author/lasteadman" title="Posts by Lauren Steadman" rel="author">Lauren Steadman</a> on Jul 20th, 2020 // <span class="comments-link">Comments off</span>					</p><!--end .postmeta-->
					<div class="entry">
						Adaptive Biotechnologies (NASDAQ:ADPT) was downgraded by Zacks Investment Research from a &#8220;buy&#8221; rating to a &#8220;hold&#8221; rating in a research report issued to clients and investors on Monday, Zacks.com reports. 
According...&nbsp;<a href='https://transcriptdaily.com/2020/07/20/adaptive-biotechnologies-nasdaqadpt-downgraded-by-zacks-investment-research.html'></a>					</div></a>
				</section> <!-- end archive -->
								<section class="archive">
					<a href="https://transcriptdaily.com/2020/07/20/plimoth-trust-co-llc-trims-position-in-automatic-data-processing-nasdaqadp.html" rel="bookmark" title="Plimoth Trust Co. LLC Trims Position in Automatic Data Processing (NASDAQ:ADP)">
					<img src="https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/automatic-data-processing-logo.png&amp;h=100&amp;w=100&amp;zc=1" alt="Plimoth Trust Co. LLC Trims Position in Automatic Data Processing (NASDAQ:ADP)" />
					<h2>Plimoth Trust Co. LLC Trims Position in Automatic Data Processing (NASDAQ:ADP)</h2>
					<p class="postmeta">
						Posted by <a href="https://transcriptdaily.com/author/jaquigley" title="Posts by James Quigley" rel="author">James Quigley</a> on Jul 20th, 2020 // <span class="comments-link">Comments off</span>					</p><!--end .postmeta-->
					<div class="entry">
						Plimoth Trust Co. LLC decreased its position in shares of  Automatic Data Processing (NASDAQ:ADP) by 3.6% during the 2nd quarter, HoldingsChannel.com reports. The institutional investor  owned 8,162 shares of the business services...&nbsp;<a href='https://transcriptdaily.com/2020/07/20/plimoth-trust-co-llc-trims-position-in-automatic-data-processing-nasdaqadp.html'></a>					</div></a>
				</section> <!-- end archive -->
								<section class="archive">
					<a href="https://transcriptdaily.com/2020/07/20/adaptive-biotechnologies-nasdaqadpt-upgraded-to-buy-by-zacks-investment-research.html" rel="bookmark" title="Adaptive Biotechnologies (NASDAQ:ADPT) Upgraded to &#8220;Buy&#8221; by Zacks Investment Research">
					<img src="https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/generic-stocks.jpg&amp;h=100&amp;w=100&amp;zc=1" alt="Adaptive Biotechnologies (NASDAQ:ADPT) Upgraded to &#8220;Buy&#8221; by Zacks Investment Research" />
					<h2>Adaptive Biotechnologies (NASDAQ:ADPT) Upgraded to &#8220;Buy&#8221; by Zacks Investment Research</h2>
					<p class="postmeta">
						Posted by <a href="https://transcriptdaily.com/author/liflegge" title="Posts by Linda Flegge" rel="author">Linda Flegge</a> on Jul 20th, 2020 // <span class="comments-link">Comments off</span>					</p><!--end .postmeta-->
					<div class="entry">
						Zacks Investment Research upgraded shares of Adaptive Biotechnologies (NASDAQ:ADPT) from a hold rating to a buy rating in a research note issued to investors on Thursday morning, Zacks.com reports. They currently have $49.00 target...&nbsp;<a href='https://transcriptdaily.com/2020/07/20/adaptive-biotechnologies-nasdaqadpt-upgraded-to-buy-by-zacks-investment-research.html'></a>					</div></a>
				</section> <!-- end archive -->
								<section class="archive">
					<a href="https://transcriptdaily.com/2020/07/18/automatic-data-processing-nasdaqadp-shares-sold-by-san-francisco-sentry-investment-group-ca.html" rel="bookmark" title="Automatic Data Processing (NASDAQ:ADP) Shares Sold by San Francisco Sentry Investment Group CA">
					<img src="https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/automatic-data-processing-logo.png&amp;h=100&amp;w=100&amp;zc=1" alt="Automatic Data Processing (NASDAQ:ADP) Shares Sold by San Francisco Sentry Investment Group CA" />
					<h2>Automatic Data Processing (NASDAQ:ADP) Shares Sold by San Francisco Sentry Investment Group CA</h2>
					<p class="postmeta">
						Posted by <a href="https://transcriptdaily.com/author/jaquigley" title="Posts by James Quigley" rel="author">James Quigley</a> on Jul 18th, 2020 // <span class="comments-link">Comments off</span>					</p><!--end .postmeta-->
					<div class="entry">
						San Francisco Sentry Investment Group CA lowered its stake in  Automatic Data Processing (NASDAQ:ADP) by 28.3% during the second quarter, HoldingsChannel reports. The firm owned 1,144 shares of the business services provider&#8217;s...&nbsp;<a href='https://transcriptdaily.com/2020/07/18/automatic-data-processing-nasdaqadp-shares-sold-by-san-francisco-sentry-investment-group-ca.html'></a>					</div></a>
				</section> <!-- end archive -->
								<section class="archive">
					<a href="https://transcriptdaily.com/2020/07/18/pennsylvania-capital-management-inc-adv-has-731000-stock-holdings-in-automatic-data-processing-nasdaqadp.html" rel="bookmark" title="Pennsylvania Capital Management Inc. ADV Has $731,000 Stock Holdings in Automatic Data Processing (NASDAQ:ADP)">
					<img src="https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/automatic-data-processing-logo.png&amp;h=100&amp;w=100&amp;zc=1" alt="Pennsylvania Capital Management Inc. ADV Has $731,000 Stock Holdings in Automatic Data Processing (NASDAQ:ADP)" />
					<h2>Pennsylvania Capital Management Inc. ADV Has $731,000 Stock Holdings in Automatic Data Processing (NASDAQ:ADP)</h2>
					<p class="postmeta">
						Posted by <a href="https://transcriptdaily.com/author/lasteadman" title="Posts by Lauren Steadman" rel="author">Lauren Steadman</a> on Jul 18th, 2020 // <span class="comments-link">Comments off</span>					</p><!--end .postmeta-->
					<div class="entry">
						Pennsylvania Capital Management Inc. ADV increased its position in shares of  Automatic Data Processing (NASDAQ:ADP) by 125.1% during the second quarter, Holdings Channel reports. The institutional investor  owned 4,910 shares of the...&nbsp;<a href='https://transcriptdaily.com/2020/07/18/pennsylvania-capital-management-inc-adv-has-731000-stock-holdings-in-automatic-data-processing-nasdaqadp.html'></a>					</div></a>
				</section> <!-- end archive -->
								<section class="archive">
					<a href="https://transcriptdaily.com/2020/07/17/298-shares-in-automatic-data-processing-nasdaqadp-bought-by-jjj-advisors-inc.html" rel="bookmark" title="298 Shares in Automatic Data Processing (NASDAQ:ADP) Bought by JJJ Advisors Inc.">
					<img src="https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/automatic-data-processing-logo.png&amp;h=100&amp;w=100&amp;zc=1" alt="298 Shares in Automatic Data Processing (NASDAQ:ADP) Bought by JJJ Advisors Inc." />
					<h2>298 Shares in Automatic Data Processing (NASDAQ:ADP) Bought by JJJ Advisors Inc.</h2>
					<p class="postmeta">
						Posted by <a href="https://transcriptdaily.com/author/lasteadman" title="Posts by Lauren Steadman" rel="author">Lauren Steadman</a> on Jul 17th, 2020 // <span class="comments-link">Comments off</span>					</p><!--end .postmeta-->
					<div class="entry">
						JJJ Advisors Inc. purchased a new position in  Automatic Data Processing (NASDAQ:ADP) in the second quarter, HoldingsChannel reports. The fund purchased 298 shares of the business services provider&#8217;s stock, valued at approximately...&nbsp;<a href='https://transcriptdaily.com/2020/07/17/298-shares-in-automatic-data-processing-nasdaqadp-bought-by-jjj-advisors-inc.html'></a>					</div></a>
				</section> <!-- end archive -->
								<section class="archive">
					<a href="https://transcriptdaily.com/2020/07/17/ado-properties-otcmktsadppf-earns-buy-rating-from-ubs-group.html" rel="bookmark" title="ADO Properties (OTCMKTS:ADPPF) Earns Buy Rating from UBS Group">
					<img src="https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/generic-stocks.jpg&amp;h=100&amp;w=100&amp;zc=1" alt="ADO Properties (OTCMKTS:ADPPF) Earns Buy Rating from UBS Group" />
					<h2>ADO Properties (OTCMKTS:ADPPF) Earns Buy Rating from UBS Group</h2>
					<p class="postmeta">
						Posted by <a href="https://transcriptdaily.com/author/jocasey" title="Posts by Joseph Casey" rel="author">Joseph Casey</a> on Jul 17th, 2020 // <span class="comments-link">Comments off</span>					</p><!--end .postmeta-->
					<div class="entry">
						UBS Group restated their buy rating on shares of ADO Properties (OTCMKTS:ADPPF)  in a research report sent to investors on Tuesday, AnalystRatings.com reports.
OTCMKTS ADPPF opened at $15.72 on Tuesday. The business has a 50 day simple...&nbsp;<a href='https://transcriptdaily.com/2020/07/17/ado-properties-otcmktsadppf-earns-buy-rating-from-ubs-group.html'></a>					</div></a>
				</section> <!-- end archive -->
								<section class="archive">
					<a href="https://transcriptdaily.com/2020/07/17/tiaa-fsb-cuts-holdings-in-automatic-data-processing-nasdaqadp.html" rel="bookmark" title="Tiaa Fsb Cuts Holdings in Automatic Data Processing (NASDAQ:ADP)">
					<img src="https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/automatic-data-processing-logo.png&amp;h=100&amp;w=100&amp;zc=1" alt="Tiaa Fsb Cuts Holdings in Automatic Data Processing (NASDAQ:ADP)" />
					<h2>Tiaa Fsb Cuts Holdings in Automatic Data Processing (NASDAQ:ADP)</h2>
					<p class="postmeta">
						Posted by <a href="https://transcriptdaily.com/author/liflegge" title="Posts by Linda Flegge" rel="author">Linda Flegge</a> on Jul 17th, 2020 // <span class="comments-link">Comments off</span>					</p><!--end .postmeta-->
					<div class="entry">
						Tiaa Fsb reduced its position in  Automatic Data Processing (NASDAQ:ADP) by 2.3% during the 2nd quarter, according to its most recent filing with the Securities and Exchange Commission. The firm owned 47,309 shares of the business...&nbsp;<a href='https://transcriptdaily.com/2020/07/17/tiaa-fsb-cuts-holdings-in-automatic-data-processing-nasdaqadp.html'></a>					</div></a>
				</section> <!-- end archive -->
								<section class="archive">
					<a href="https://transcriptdaily.com/2020/07/16/automatic-data-processing-nasdaqadp-now-covered-by-goldman-sachs-group.html" rel="bookmark" title="Automatic Data Processing (NASDAQ:ADP) Now Covered by Goldman Sachs Group">
					<img src="https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/automatic-data-processing-logo.png&amp;h=100&amp;w=100&amp;zc=1" alt="Automatic Data Processing (NASDAQ:ADP) Now Covered by Goldman Sachs Group" />
					<h2>Automatic Data Processing (NASDAQ:ADP) Now Covered by Goldman Sachs Group</h2>
					<p class="postmeta">
						Posted by <a href="https://transcriptdaily.com/author/cawalker" title="Posts by Casey Walker" rel="author">Casey Walker</a> on Jul 16th, 2020 // <span class="comments-link">Comments off</span>					</p><!--end .postmeta-->
					<div class="entry">
						Investment analysts at Goldman Sachs Group assumed coverage on shares of Automatic Data Processing (NASDAQ:ADP) in a report issued on Tuesday, MarketBeat Ratings reports. The brokerage set a &#8220;sell&#8221; rating and a $146.00...&nbsp;<a href='https://transcriptdaily.com/2020/07/16/automatic-data-processing-nasdaqadp-now-covered-by-goldman-sachs-group.html'></a>					</div></a>
				</section> <!-- end archive -->
								<section class="archive">
					<a href="https://transcriptdaily.com/2020/07/14/boenning-scattergood-inc-trims-holdings-in-automatic-data-processing-nasdaqadp.html" rel="bookmark" title="Boenning &#038; Scattergood Inc. Trims Holdings in Automatic Data Processing (NASDAQ:ADP)">
					<img src="https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/automatic-data-processing-logo.png&amp;h=100&amp;w=100&amp;zc=1" alt="Boenning &#038; Scattergood Inc. Trims Holdings in Automatic Data Processing (NASDAQ:ADP)" />
					<h2>Boenning &#038; Scattergood Inc. Trims Holdings in Automatic Data Processing (NASDAQ:ADP)</h2>
					<p class="postmeta">
						Posted by <a href="https://transcriptdaily.com/author/jocasey" title="Posts by Joseph Casey" rel="author">Joseph Casey</a> on Jul 14th, 2020 // <span class="comments-link">Comments off</span>					</p><!--end .postmeta-->
					<div class="entry">
						Boenning &#038; Scattergood Inc. trimmed its holdings in shares of  Automatic Data Processing (NASDAQ:ADP) by 1.1% in the 2nd quarter, Holdings Channel.com reports. The institutional investor  owned 9,454 shares of the business services...&nbsp;<a href='https://transcriptdaily.com/2020/07/14/boenning-scattergood-inc-trims-holdings-in-automatic-data-processing-nasdaqadp.html'></a>					</div></a>
				</section> <!-- end archive -->
								<section class="archive">
					<a href="https://transcriptdaily.com/2020/07/14/northwest-investment-counselors-llc-sells-164-shares-of-automatic-data-processing-nasdaqadp.html" rel="bookmark" title="Northwest Investment Counselors LLC Sells 164 Shares of Automatic Data Processing (NASDAQ:ADP)">
					<img src="https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/automatic-data-processing-logo.png&amp;h=100&amp;w=100&amp;zc=1" alt="Northwest Investment Counselors LLC Sells 164 Shares of Automatic Data Processing (NASDAQ:ADP)" />
					<h2>Northwest Investment Counselors LLC Sells 164 Shares of Automatic Data Processing (NASDAQ:ADP)</h2>
					<p class="postmeta">
						Posted by <a href="https://transcriptdaily.com/author/liflegge" title="Posts by Linda Flegge" rel="author">Linda Flegge</a> on Jul 14th, 2020 // <span class="comments-link">Comments off</span>					</p><!--end .postmeta-->
					<div class="entry">
						Northwest Investment Counselors LLC lowered its stake in shares of  Automatic Data Processing (NASDAQ:ADP) by 0.8% during the 2nd quarter, according to the company in its most recent disclosure with the Securities and Exchange Commission...&nbsp;<a href='https://transcriptdaily.com/2020/07/14/northwest-investment-counselors-llc-sells-164-shares-of-automatic-data-processing-nasdaqadp.html'></a>					</div></a>
				</section> <!-- end archive -->
								<section class="archive">
					<a href="https://transcriptdaily.com/2020/07/13/automatic-data-processing-nasdaqadp-vp-brian-l-michaud-sells-250-shares.html" rel="bookmark" title="Automatic Data Processing (NASDAQ:ADP) VP Brian L. Michaud Sells 250 Shares">
					<img src="https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/automatic-data-processing-logo.png&amp;h=100&amp;w=100&amp;zc=1" alt="Automatic Data Processing (NASDAQ:ADP) VP Brian L. Michaud Sells 250 Shares" />
					<h2>Automatic Data Processing (NASDAQ:ADP) VP Brian L. Michaud Sells 250 Shares</h2>
					<p class="postmeta">
						Posted by <a href="https://transcriptdaily.com/author/liflegge" title="Posts by Linda Flegge" rel="author">Linda Flegge</a> on Jul 13th, 2020 // <span class="comments-link">Comments off</span>					</p><!--end .postmeta-->
					<div class="entry">
						Automatic Data Processing (NASDAQ:ADP) VP Brian L. Michaud sold 250 shares of the business&#8217;s stock in a transaction on Friday, July 10th. The stock was sold at an average price of $145.00, for a total transaction of $36,250.00....&nbsp;<a href='https://transcriptdaily.com/2020/07/13/automatic-data-processing-nasdaqadp-vp-brian-l-michaud-sells-250-shares.html'></a>					</div></a>
				</section> <!-- end archive -->
								<section class="archive">
					<a href="https://transcriptdaily.com/2020/07/13/insider-selling-adaptive-biotechnologies-corporation-nasdaqadpt-president-sells-748475-00-in-stock.html" rel="bookmark" title="Insider Selling: Adaptive Biotechnologies Corporation (NASDAQ:ADPT) President Sells $748,475.00 in Stock">
					<img src="https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/generic-stocks.jpg&amp;h=100&amp;w=100&amp;zc=1" alt="Insider Selling: Adaptive Biotechnologies Corporation (NASDAQ:ADPT) President Sells $748,475.00 in Stock" />
					<h2>Insider Selling: Adaptive Biotechnologies Corporation (NASDAQ:ADPT) President Sells $748,475.00 in Stock</h2>
					<p class="postmeta">
						Posted by <a href="https://transcriptdaily.com/author/jaquigley" title="Posts by James Quigley" rel="author">James Quigley</a> on Jul 13th, 2020 // <span class="comments-link">Comments off</span>					</p><!--end .postmeta-->
					<div class="entry">
						Adaptive Biotechnologies Corporation (NASDAQ:ADPT) President Julie Rubinstein sold 15,275 shares of Adaptive Biotechnologies stock in a transaction on Thursday, July 9th. The stock was sold at an average price of $49.00, for a total...&nbsp;<a href='https://transcriptdaily.com/2020/07/13/insider-selling-adaptive-biotechnologies-corporation-nasdaqadpt-president-sells-748475-00-in-stock.html'></a>					</div></a>
				</section> <!-- end archive -->
								<section class="archive">
					<a href="https://transcriptdaily.com/2020/07/12/adaptive-biotechnologies-corporation-nasdaqadpt-director-sells-473700-00-in-stock.html" rel="bookmark" title="Adaptive Biotechnologies Corporation (NASDAQ:ADPT) Director Sells $473,700.00 in Stock">
					<img src="https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/generic-stocks.jpg&amp;h=100&amp;w=100&amp;zc=1" alt="Adaptive Biotechnologies Corporation (NASDAQ:ADPT) Director Sells $473,700.00 in Stock" />
					<h2>Adaptive Biotechnologies Corporation (NASDAQ:ADPT) Director Sells $473,700.00 in Stock</h2>
					<p class="postmeta">
						Posted by <a href="https://transcriptdaily.com/author/lasteadman" title="Posts by Lauren Steadman" rel="author">Lauren Steadman</a> on Jul 12th, 2020 // <span class="comments-link">Comments off</span>					</p><!--end .postmeta-->
					<div class="entry">
						Adaptive Biotechnologies Corporation (NASDAQ:ADPT) Director Eric Dobmeier sold 10,000 shares of the stock in a transaction on Monday, July 6th. The shares were sold at an average price of $47.37, for a total value of $473,700.00. Following...&nbsp;<a href='https://transcriptdaily.com/2020/07/12/adaptive-biotechnologies-corporation-nasdaqadpt-director-sells-473700-00-in-stock.html'></a>					</div></a>
				</section> <!-- end archive -->
								<section class="archive">
					<a href="https://transcriptdaily.com/2020/07/11/adaptive-biotechnologies-corporation-nasdaqadpt-given-average-recommendation-of-buy-by-brokerages.html" rel="bookmark" title="Adaptive Biotechnologies Corporation (NASDAQ:ADPT) Given Average Recommendation of &#8220;Buy&#8221; by Brokerages">
					<img src="https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/generic-stocks.jpg&amp;h=100&amp;w=100&amp;zc=1" alt="Adaptive Biotechnologies Corporation (NASDAQ:ADPT) Given Average Recommendation of &#8220;Buy&#8221; by Brokerages" />
					<h2>Adaptive Biotechnologies Corporation (NASDAQ:ADPT) Given Average Recommendation of &#8220;Buy&#8221; by Brokerages</h2>
					<p class="postmeta">
						Posted by <a href="https://transcriptdaily.com/author/cawalker" title="Posts by Casey Walker" rel="author">Casey Walker</a> on Jul 11th, 2020 // <span class="comments-link">Comments off</span>					</p><!--end .postmeta-->
					<div class="entry">
						Shares of Adaptive Biotechnologies Corporation (NASDAQ:ADPT) have been given an average rating of &#8220;Buy&#8221; by the nine analysts that are currently  covering the firm, Marketbeat Ratings reports. Two equities research analysts...&nbsp;<a href='https://transcriptdaily.com/2020/07/11/adaptive-biotechnologies-corporation-nasdaqadpt-given-average-recommendation-of-buy-by-brokerages.html'></a>					</div></a>
				</section> <!-- end archive -->
								<section class="archive">
					<a href="https://transcriptdaily.com/2020/07/10/cypress-capital-group-sells-2234-shares-of-automatic-data-processing-nasdaqadp.html" rel="bookmark" title="Cypress Capital Group Sells 2,234 Shares of Automatic Data Processing (NASDAQ:ADP)">
					<img src="https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/automatic-data-processing-logo.png&amp;h=100&amp;w=100&amp;zc=1" alt="Cypress Capital Group Sells 2,234 Shares of Automatic Data Processing (NASDAQ:ADP)" />
					<h2>Cypress Capital Group Sells 2,234 Shares of Automatic Data Processing (NASDAQ:ADP)</h2>
					<p class="postmeta">
						Posted by <a href="https://transcriptdaily.com/author/cawalker" title="Posts by Casey Walker" rel="author">Casey Walker</a> on Jul 10th, 2020 // <span class="comments-link">Comments off</span>					</p><!--end .postmeta-->
					<div class="entry">
						Cypress Capital Group lowered its holdings in shares of  Automatic Data Processing (NASDAQ:ADP) by 21.0% in the second quarter, according to its most recent disclosure with the SEC. The firm owned 8,380 shares of the business services...&nbsp;<a href='https://transcriptdaily.com/2020/07/10/cypress-capital-group-sells-2234-shares-of-automatic-data-processing-nasdaqadp.html'></a>					</div></a>
				</section> <!-- end archive -->
								<section class="archive">
					<a href="https://transcriptdaily.com/2020/07/10/contrasting-adaptive-biotechnologies-nasdaqadpt-and-spark-therapeutics-nasdaqonce.html" rel="bookmark" title="Contrasting Adaptive Biotechnologies (NASDAQ:ADPT) and Spark Therapeutics (NASDAQ:ONCE)">
					<img src="https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/spark-therapeutics-inc-logo.png&amp;h=100&amp;w=100&amp;zc=1" alt="Contrasting Adaptive Biotechnologies (NASDAQ:ADPT) and Spark Therapeutics (NASDAQ:ONCE)" />
					<h2>Contrasting Adaptive Biotechnologies (NASDAQ:ADPT) and Spark Therapeutics (NASDAQ:ONCE)</h2>
					<p class="postmeta">
						Posted by <a href="https://transcriptdaily.com/author/lasteadman" title="Posts by Lauren Steadman" rel="author">Lauren Steadman</a> on Jul 10th, 2020 // <span class="comments-link">Comments off</span>					</p><!--end .postmeta-->
					<div class="entry">
						Adaptive Biotechnologies (NASDAQ:ADPT) and Spark Therapeutics (NASDAQ:ONCE) are both mid-cap medical companies, but which is the better business? We will compare the two companies based on the strength of their profitability, earnings,...&nbsp;<a href='https://transcriptdaily.com/2020/07/10/contrasting-adaptive-biotechnologies-nasdaqadpt-and-spark-therapeutics-nasdaqonce.html'></a>					</div></a>
				</section> <!-- end archive -->
								<section class="archive">
					<a href="https://transcriptdaily.com/2020/07/09/univest-financial-corp-buys-4460-shares-of-automatic-data-processing-nasdaqadp.html" rel="bookmark" title="UNIVEST FINANCIAL Corp Buys 4,460 Shares of Automatic Data Processing (NASDAQ:ADP)">
					<img src="https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/automatic-data-processing-logo.png&amp;h=100&amp;w=100&amp;zc=1" alt="UNIVEST FINANCIAL Corp Buys 4,460 Shares of Automatic Data Processing (NASDAQ:ADP)" />
					<h2>UNIVEST FINANCIAL Corp Buys 4,460 Shares of Automatic Data Processing (NASDAQ:ADP)</h2>
					<p class="postmeta">
						Posted by <a href="https://transcriptdaily.com/author/liflegge" title="Posts by Linda Flegge" rel="author">Linda Flegge</a> on Jul 9th, 2020 // <span class="comments-link">Comments off</span>					</p><!--end .postmeta-->
					<div class="entry">
						UNIVEST FINANCIAL Corp increased its holdings in  Automatic Data Processing (NASDAQ:ADP) by 12.7% in the 2nd quarter, according to its most recent filing with the SEC. The institutional investor  owned 39,706 shares of the business...&nbsp;<a href='https://transcriptdaily.com/2020/07/09/univest-financial-corp-buys-4460-shares-of-automatic-data-processing-nasdaqadp.html'></a>					</div></a>
				</section> <!-- end archive -->
								<section class="archive">
					<a href="https://transcriptdaily.com/2020/07/08/home-federal-bank-of-tennessee-sells-300-shares-of-automatic-data-processing-nasdaqadp.html" rel="bookmark" title="Home Federal Bank of Tennessee Sells 300 Shares of Automatic Data Processing (NASDAQ:ADP)">
					<img src="https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/automatic-data-processing-logo.png&amp;h=100&amp;w=100&amp;zc=1" alt="Home Federal Bank of Tennessee Sells 300 Shares of Automatic Data Processing (NASDAQ:ADP)" />
					<h2>Home Federal Bank of Tennessee Sells 300 Shares of Automatic Data Processing (NASDAQ:ADP)</h2>
					<p class="postmeta">
						Posted by <a href="https://transcriptdaily.com/author/lasteadman" title="Posts by Lauren Steadman" rel="author">Lauren Steadman</a> on Jul 8th, 2020 // <span class="comments-link">Comments off</span>					</p><!--end .postmeta-->
					<div class="entry">
						Home Federal Bank of Tennessee cut its holdings in  Automatic Data Processing (NASDAQ:ADP) by 2.4% in the 2nd quarter, according to its most recent Form 13F filing with the Securities &amp; Exchange Commission. The fund owned 12,285...&nbsp;<a href='https://transcriptdaily.com/2020/07/08/home-federal-bank-of-tennessee-sells-300-shares-of-automatic-data-processing-nasdaqadp.html'></a>					</div></a>
				</section> <!-- end archive -->
								<section class="archive">
					<a href="https://transcriptdaily.com/2020/07/08/automatic-data-processing-nasdaqadp-receives-average-rating-of-hold-from-analysts.html" rel="bookmark" title="Automatic Data Processing (NASDAQ:ADP) Receives Average Rating of &#8220;Hold&#8221; from Analysts">
					<img src="https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/automatic-data-processing-logo.png&amp;h=100&amp;w=100&amp;zc=1" alt="Automatic Data Processing (NASDAQ:ADP) Receives Average Rating of &#8220;Hold&#8221; from Analysts" />
					<h2>Automatic Data Processing (NASDAQ:ADP) Receives Average Rating of &#8220;Hold&#8221; from Analysts</h2>
					<p class="postmeta">
						Posted by <a href="https://transcriptdaily.com/author/jocasey" title="Posts by Joseph Casey" rel="author">Joseph Casey</a> on Jul 8th, 2020 // <span class="comments-link">Comments off</span>					</p><!--end .postmeta-->
					<div class="entry">
						Shares of Automatic Data Processing (NASDAQ:ADP) have been assigned an average recommendation of &#8220;Hold&#8221; from the nineteen research firms that are currently  covering the stock, MarketBeat reports. One equities research...&nbsp;<a href='https://transcriptdaily.com/2020/07/08/automatic-data-processing-nasdaqadp-receives-average-rating-of-hold-from-analysts.html'></a>					</div></a>
				</section> <!-- end archive -->
								<section class="archive">
					<a href="https://transcriptdaily.com/2020/07/08/bangor-savings-bank-has-900000-stock-holdings-in-automatic-data-processing-nasdaqadp.html" rel="bookmark" title="Bangor Savings Bank Has $900,000 Stock Holdings in Automatic Data Processing (NASDAQ:ADP)">
					<img src="https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/automatic-data-processing-logo.png&amp;h=100&amp;w=100&amp;zc=1" alt="Bangor Savings Bank Has $900,000 Stock Holdings in Automatic Data Processing (NASDAQ:ADP)" />
					<h2>Bangor Savings Bank Has $900,000 Stock Holdings in Automatic Data Processing (NASDAQ:ADP)</h2>
					<p class="postmeta">
						Posted by <a href="https://transcriptdaily.com/author/cawalker" title="Posts by Casey Walker" rel="author">Casey Walker</a> on Jul 8th, 2020 // <span class="comments-link">Comments off</span>					</p><!--end .postmeta-->
					<div class="entry">
						Bangor Savings Bank cut its position in shares of  Automatic Data Processing (NASDAQ:ADP) by 2.2% during the 2nd quarter, according to its most recent filing with the Securities and Exchange Commission (SEC). The fund owned 6,043 shares...&nbsp;<a href='https://transcriptdaily.com/2020/07/08/bangor-savings-bank-has-900000-stock-holdings-in-automatic-data-processing-nasdaqadp.html'></a>					</div></a>
				</section> <!-- end archive -->
								<section class="archive">
					<a href="https://transcriptdaily.com/2020/07/07/renaissance-investment-group-llc-cuts-stock-holdings-in-automatic-data-processing-nasdaqadp.html" rel="bookmark" title="Renaissance Investment Group LLC Cuts Stock Holdings in Automatic Data Processing (NASDAQ:ADP)">
					<img src="https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/automatic-data-processing-logo.png&amp;h=100&amp;w=100&amp;zc=1" alt="Renaissance Investment Group LLC Cuts Stock Holdings in Automatic Data Processing (NASDAQ:ADP)" />
					<h2>Renaissance Investment Group LLC Cuts Stock Holdings in Automatic Data Processing (NASDAQ:ADP)</h2>
					<p class="postmeta">
						Posted by <a href="https://transcriptdaily.com/author/cawalker" title="Posts by Casey Walker" rel="author">Casey Walker</a> on Jul 7th, 2020 // <span class="comments-link">Comments off</span>					</p><!--end .postmeta-->
					<div class="entry">
						Renaissance Investment Group LLC reduced its position in shares of  Automatic Data Processing (NASDAQ:ADP) by 18.8% in the 2nd quarter, according to its most recent disclosure with the Securities &amp; Exchange Commission. The institutional...&nbsp;<a href='https://transcriptdaily.com/2020/07/07/renaissance-investment-group-llc-cuts-stock-holdings-in-automatic-data-processing-nasdaqadp.html'></a>					</div></a>
				</section> <!-- end archive -->
								<section class="archive">
					<a href="https://transcriptdaily.com/2020/07/07/woodstock-corp-has-10-50-million-position-in-automatic-data-processing-nasdaqadp.html" rel="bookmark" title="Woodstock Corp Has $10.50 Million Position in Automatic Data Processing (NASDAQ:ADP)">
					<img src="https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/automatic-data-processing-logo.png&amp;h=100&amp;w=100&amp;zc=1" alt="Woodstock Corp Has $10.50 Million Position in Automatic Data Processing (NASDAQ:ADP)" />
					<h2>Woodstock Corp Has $10.50 Million Position in Automatic Data Processing (NASDAQ:ADP)</h2>
					<p class="postmeta">
						Posted by <a href="https://transcriptdaily.com/author/liflegge" title="Posts by Linda Flegge" rel="author">Linda Flegge</a> on Jul 7th, 2020 // <span class="comments-link">Comments off</span>					</p><!--end .postmeta-->
					<div class="entry">
						Woodstock Corp trimmed its position in  Automatic Data Processing (NASDAQ:ADP) by 0.5% during the second quarter, according to its most recent 13F filing with the SEC. The fund owned 70,489 shares of the business services provider&#8217;s...&nbsp;<a href='https://transcriptdaily.com/2020/07/07/woodstock-corp-has-10-50-million-position-in-automatic-data-processing-nasdaqadp.html'></a>					</div></a>
				</section> <!-- end archive -->
								<section class="archive">
					<a href="https://transcriptdaily.com/2020/07/07/pinnacle-bank-has-682000-stock-position-in-automatic-data-processing-nasdaqadp.html" rel="bookmark" title="Pinnacle Bank Has $682,000 Stock Position in Automatic Data Processing (NASDAQ:ADP)">
					<img src="https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/automatic-data-processing-logo.png&amp;h=100&amp;w=100&amp;zc=1" alt="Pinnacle Bank Has $682,000 Stock Position in Automatic Data Processing (NASDAQ:ADP)" />
					<h2>Pinnacle Bank Has $682,000 Stock Position in Automatic Data Processing (NASDAQ:ADP)</h2>
					<p class="postmeta">
						Posted by <a href="https://transcriptdaily.com/author/cawalker" title="Posts by Casey Walker" rel="author">Casey Walker</a> on Jul 7th, 2020 // <span class="comments-link">Comments off</span>					</p><!--end .postmeta-->
					<div class="entry">
						Pinnacle Bank lowered its holdings in  Automatic Data Processing (NASDAQ:ADP) by 4.5% during the second quarter, according to its most recent filing with the Securities &amp; Exchange Commission. The fund owned 4,583 shares of the...&nbsp;<a href='https://transcriptdaily.com/2020/07/07/pinnacle-bank-has-682000-stock-position-in-automatic-data-processing-nasdaqadp.html'></a>					</div></a>
				</section> <!-- end archive -->
								<section class="archive">
					<a href="https://transcriptdaily.com/2020/07/07/municipal-employees-retirement-system-of-michigan-has-2-38-million-stake-in-automatic-data-processing-nasdaqadp.html" rel="bookmark" title="Municipal Employees Retirement System of Michigan Has $2.38 Million Stake in Automatic Data Processing (NASDAQ:ADP)">
					<img src="https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/automatic-data-processing-logo.png&amp;h=100&amp;w=100&amp;zc=1" alt="Municipal Employees Retirement System of Michigan Has $2.38 Million Stake in Automatic Data Processing (NASDAQ:ADP)" />
					<h2>Municipal Employees Retirement System of Michigan Has $2.38 Million Stake in Automatic Data Processing (NASDAQ:ADP)</h2>
					<p class="postmeta">
						Posted by <a href="https://transcriptdaily.com/author/cawalker" title="Posts by Casey Walker" rel="author">Casey Walker</a> on Jul 7th, 2020 // <span class="comments-link">Comments off</span>					</p><!--end .postmeta-->
					<div class="entry">
						Municipal Employees Retirement System of Michigan raised its stake in shares of  Automatic Data Processing (NASDAQ:ADP) by 158.2% in the second quarter, according to its most recent 13F filing with the SEC. The fund owned 16,010 shares...&nbsp;<a href='https://transcriptdaily.com/2020/07/07/municipal-employees-retirement-system-of-michigan-has-2-38-million-stake-in-automatic-data-processing-nasdaqadp.html'></a>					</div></a>
				</section> <!-- end archive -->
								<section class="archive">
					<a href="https://transcriptdaily.com/2020/07/07/west-oak-capital-llc-purchases-635-shares-of-automatic-data-processing-nasdaqadp.html" rel="bookmark" title="West Oak Capital LLC Purchases 635 Shares of Automatic Data Processing (NASDAQ:ADP)">
					<img src="https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/automatic-data-processing-logo.png&amp;h=100&amp;w=100&amp;zc=1" alt="West Oak Capital LLC Purchases 635 Shares of Automatic Data Processing (NASDAQ:ADP)" />
					<h2>West Oak Capital LLC Purchases 635 Shares of Automatic Data Processing (NASDAQ:ADP)</h2>
					<p class="postmeta">
						Posted by <a href="https://transcriptdaily.com/author/liflegge" title="Posts by Linda Flegge" rel="author">Linda Flegge</a> on Jul 7th, 2020 // <span class="comments-link">Comments off</span>					</p><!--end .postmeta-->
					<div class="entry">
						West Oak Capital LLC raised its position in shares of  Automatic Data Processing (NASDAQ:ADP) by 3.3% in the 2nd quarter, according to the company in its most recent Form 13F filing with the Securities and Exchange Commission. The...&nbsp;<a href='https://transcriptdaily.com/2020/07/07/west-oak-capital-llc-purchases-635-shares-of-automatic-data-processing-nasdaqadp.html'></a>					</div></a>
				</section> <!-- end archive -->
								<section class="archive">
					<a href="https://transcriptdaily.com/2020/07/06/hummer-financial-advisory-services-inc-raises-stake-in-automatic-data-processing-nasdaqadp.html" rel="bookmark" title="Hummer Financial Advisory Services Inc Raises Stake in Automatic Data Processing (NASDAQ:ADP)">
					<img src="https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/automatic-data-processing-logo.png&amp;h=100&amp;w=100&amp;zc=1" alt="Hummer Financial Advisory Services Inc Raises Stake in Automatic Data Processing (NASDAQ:ADP)" />
					<h2>Hummer Financial Advisory Services Inc Raises Stake in Automatic Data Processing (NASDAQ:ADP)</h2>
					<p class="postmeta">
						Posted by <a href="https://transcriptdaily.com/author/liflegge" title="Posts by Linda Flegge" rel="author">Linda Flegge</a> on Jul 6th, 2020 // <span class="comments-link">Comments off</span>					</p><!--end .postmeta-->
					<div class="entry">
						Hummer Financial Advisory Services Inc grew its stake in shares of  Automatic Data Processing (NASDAQ:ADP) by 2.8% during the 2nd quarter, according to its most recent 13F filing with the SEC. The institutional investor  owned 5,550...&nbsp;<a href='https://transcriptdaily.com/2020/07/06/hummer-financial-advisory-services-inc-raises-stake-in-automatic-data-processing-nasdaqadp.html'></a>					</div></a>
				</section> <!-- end archive -->
								<section class="archive">
					<a href="https://transcriptdaily.com/2020/07/06/insider-selling-adaptive-biotechnologies-corporation-nasdaqadpt-evp-sells-142260-00-in-stock.html" rel="bookmark" title="Insider Selling: Adaptive Biotechnologies Corporation (NASDAQ:ADPT) EVP Sells $142,260.00 in Stock">
					<img src="https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/generic-stocks.jpg&amp;h=100&amp;w=100&amp;zc=1" alt="Insider Selling: Adaptive Biotechnologies Corporation (NASDAQ:ADPT) EVP Sells $142,260.00 in Stock" />
					<h2>Insider Selling: Adaptive Biotechnologies Corporation (NASDAQ:ADPT) EVP Sells $142,260.00 in Stock</h2>
					<p class="postmeta">
						Posted by <a href="https://transcriptdaily.com/author/cawalker" title="Posts by Casey Walker" rel="author">Casey Walker</a> on Jul 6th, 2020 // <span class="comments-link">Comments off</span>					</p><!--end .postmeta-->
					<div class="entry">
						Adaptive Biotechnologies Corporation (NASDAQ:ADPT) EVP Nancy Louise Hill sold 3,000 shares of the stock in a transaction dated Wednesday, July 1st. The stock was sold at an average price of $47.42, for a total value of $142,260.00....&nbsp;<a href='https://transcriptdaily.com/2020/07/06/insider-selling-adaptive-biotechnologies-corporation-nasdaqadpt-evp-sells-142260-00-in-stock.html'></a>					</div></a>
				</section> <!-- end archive -->
								<section class="archive">
					<a href="https://transcriptdaily.com/2020/07/06/adaptive-biotechnologies-corporation-nasdaqadpt-insider-sells-320539-14-in-stock.html" rel="bookmark" title="Adaptive Biotechnologies Corporation (NASDAQ:ADPT) Insider Sells $320,539.14 in Stock">
					<img src="https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/generic-stocks.jpg&amp;h=100&amp;w=100&amp;zc=1" alt="Adaptive Biotechnologies Corporation (NASDAQ:ADPT) Insider Sells $320,539.14 in Stock" />
					<h2>Adaptive Biotechnologies Corporation (NASDAQ:ADPT) Insider Sells $320,539.14 in Stock</h2>
					<p class="postmeta">
						Posted by <a href="https://transcriptdaily.com/author/liflegge" title="Posts by Linda Flegge" rel="author">Linda Flegge</a> on Jul 6th, 2020 // <span class="comments-link">Comments off</span>					</p><!--end .postmeta-->
					<div class="entry">
						Adaptive Biotechnologies Corporation (NASDAQ:ADPT) insider Sharon Benzeno sold 6,771 shares of Adaptive Biotechnologies stock in a transaction that occurred on Wednesday, July 1st. The stock was sold at an average price of $47.34,...&nbsp;<a href='https://transcriptdaily.com/2020/07/06/adaptive-biotechnologies-corporation-nasdaqadpt-insider-sells-320539-14-in-stock.html'></a>					</div></a>
				</section> <!-- end archive -->
								<section class="archive">
					<a href="https://transcriptdaily.com/2020/07/03/adaptive-biotechnologies-nasdaqadpt-downgraded-to-hold-at-valuengine.html" rel="bookmark" title="Adaptive Biotechnologies (NASDAQ:ADPT) Downgraded to &#8220;Hold&#8221; at ValuEngine">
					<img src="https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/generic-stocks.jpg&amp;h=100&amp;w=100&amp;zc=1" alt="Adaptive Biotechnologies (NASDAQ:ADPT) Downgraded to &#8220;Hold&#8221; at ValuEngine" />
					<h2>Adaptive Biotechnologies (NASDAQ:ADPT) Downgraded to &#8220;Hold&#8221; at ValuEngine</h2>
					<p class="postmeta">
						Posted by <a href="https://transcriptdaily.com/author/jocasey" title="Posts by Joseph Casey" rel="author">Joseph Casey</a> on Jul 3rd, 2020 // <span class="comments-link">Comments off</span>					</p><!--end .postmeta-->
					<div class="entry">
						ValuEngine cut shares of Adaptive Biotechnologies (NASDAQ:ADPT) from a buy rating to a hold rating in a research note released on Thursday morning, ValuEngine reports.
Several other research analysts also recently commented on ADPT....&nbsp;<a href='https://transcriptdaily.com/2020/07/03/adaptive-biotechnologies-nasdaqadpt-downgraded-to-hold-at-valuengine.html'></a>					</div></a>
				</section> <!-- end archive -->
								<section class="archive">
					<a href="https://transcriptdaily.com/2020/07/02/first-financial-bank-trust-division-sells-311-shares-of-automatic-data-processing-nasdaqadp.html" rel="bookmark" title="First Financial Bank Trust Division Sells 311 Shares of Automatic Data Processing (NASDAQ:ADP)">
					<img src="https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/automatic-data-processing-logo.png&amp;h=100&amp;w=100&amp;zc=1" alt="First Financial Bank Trust Division Sells 311 Shares of Automatic Data Processing (NASDAQ:ADP)" />
					<h2>First Financial Bank Trust Division Sells 311 Shares of Automatic Data Processing (NASDAQ:ADP)</h2>
					<p class="postmeta">
						Posted by <a href="https://transcriptdaily.com/author/cawalker" title="Posts by Casey Walker" rel="author">Casey Walker</a> on Jul 2nd, 2020 // <span class="comments-link">Comments off</span>					</p><!--end .postmeta-->
					<div class="entry">
						First Financial Bank Trust Division decreased its holdings in  Automatic Data Processing (NASDAQ:ADP) by 3.0% during the 2nd quarter, according to the company in its most recent disclosure with the Securities &amp; Exchange Commission....&nbsp;<a href='https://transcriptdaily.com/2020/07/02/first-financial-bank-trust-division-sells-311-shares-of-automatic-data-processing-nasdaqadp.html'></a>					</div></a>
				</section> <!-- end archive -->
								<section class="archive">
					<a href="https://transcriptdaily.com/2020/07/02/boltwood-capital-management-trims-position-in-automatic-data-processing-nasdaqadp.html" rel="bookmark" title="Boltwood Capital Management Trims Position in Automatic Data Processing (NASDAQ:ADP)">
					<img src="https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/automatic-data-processing-logo.png&amp;h=100&amp;w=100&amp;zc=1" alt="Boltwood Capital Management Trims Position in Automatic Data Processing (NASDAQ:ADP)" />
					<h2>Boltwood Capital Management Trims Position in Automatic Data Processing (NASDAQ:ADP)</h2>
					<p class="postmeta">
						Posted by <a href="https://transcriptdaily.com/author/jaquigley" title="Posts by James Quigley" rel="author">James Quigley</a> on Jul 2nd, 2020 // <span class="comments-link">Comments off</span>					</p><!--end .postmeta-->
					<div class="entry">
						Boltwood Capital Management lessened its position in shares of  Automatic Data Processing (NASDAQ:ADP) by 1.8% in the second quarter, according to the company in its most recent Form 13F filing with the SEC. The fund owned 5,600 shares...&nbsp;<a href='https://transcriptdaily.com/2020/07/02/boltwood-capital-management-trims-position-in-automatic-data-processing-nasdaqadp.html'></a>					</div></a>
				</section> <!-- end archive -->
								<section class="archive">
					<a href="https://transcriptdaily.com/2020/07/02/mr-capital-management-inc-has-458000-position-in-automatic-data-processing-nasdaqadp.html" rel="bookmark" title="M&#038;R Capital Management Inc. Has $458,000 Position in Automatic Data Processing (NASDAQ:ADP)">
					<img src="https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/automatic-data-processing-logo.png&amp;h=100&amp;w=100&amp;zc=1" alt="M&#038;R Capital Management Inc. Has $458,000 Position in Automatic Data Processing (NASDAQ:ADP)" />
					<h2>M&#038;R Capital Management Inc. Has $458,000 Position in Automatic Data Processing (NASDAQ:ADP)</h2>
					<p class="postmeta">
						Posted by <a href="https://transcriptdaily.com/author/jocasey" title="Posts by Joseph Casey" rel="author">Joseph Casey</a> on Jul 2nd, 2020 // <span class="comments-link">Comments off</span>					</p><!--end .postmeta-->
					<div class="entry">
						M&#038;R Capital Management Inc. lowered its stake in  Automatic Data Processing (NASDAQ:ADP) by 9.3% in the second quarter, according to the company in its most recent disclosure with the Securities and Exchange Commission (SEC)....&nbsp;<a href='https://transcriptdaily.com/2020/07/02/mr-capital-management-inc-has-458000-position-in-automatic-data-processing-nasdaqadp.html'></a>					</div></a>
				</section> <!-- end archive -->
								<section class="archive">
					<a href="https://transcriptdaily.com/2020/06/29/0-96-earnings-per-share-expected-for-automatic-data-processing-nasdaqadp-this-quarter.html" rel="bookmark" title="$0.96 Earnings Per Share Expected for Automatic Data Processing (NASDAQ:ADP) This Quarter">
					<img src="https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/automatic-data-processing-logo.png&amp;h=100&amp;w=100&amp;zc=1" alt="$0.96 Earnings Per Share Expected for Automatic Data Processing (NASDAQ:ADP) This Quarter" />
					<h2>$0.96 Earnings Per Share Expected for Automatic Data Processing (NASDAQ:ADP) This Quarter</h2>
					<p class="postmeta">
						Posted by <a href="https://transcriptdaily.com/author/jaquigley" title="Posts by James Quigley" rel="author">James Quigley</a> on Jun 29th, 2020 // <span class="comments-link">Comments off</span>					</p><!--end .postmeta-->
					<div class="entry">
						Analysts expect that Automatic Data Processing (NASDAQ:ADP) will post earnings per share of $0.96 for the current quarter, Zacks reports. Six analysts have provided estimates for Automatic Data Processing&#8217;s earnings, with the...&nbsp;<a href='https://transcriptdaily.com/2020/06/29/0-96-earnings-per-share-expected-for-automatic-data-processing-nasdaqadp-this-quarter.html'></a>					</div></a>
				</section> <!-- end archive -->
								<section class="archive">
					<a href="https://transcriptdaily.com/2020/06/29/automatic-data-processing-nasdaqadp-expected-to-post-quarterly-sales-of-3-29-billion.html" rel="bookmark" title="Automatic Data Processing (NASDAQ:ADP) Expected to Post Quarterly Sales of $3.29 Billion">
					<img src="https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/automatic-data-processing-logo.png&amp;h=100&amp;w=100&amp;zc=1" alt="Automatic Data Processing (NASDAQ:ADP) Expected to Post Quarterly Sales of $3.29 Billion" />
					<h2>Automatic Data Processing (NASDAQ:ADP) Expected to Post Quarterly Sales of $3.29 Billion</h2>
					<p class="postmeta">
						Posted by <a href="https://transcriptdaily.com/author/lasteadman" title="Posts by Lauren Steadman" rel="author">Lauren Steadman</a> on Jun 29th, 2020 // <span class="comments-link">Comments off</span>					</p><!--end .postmeta-->
					<div class="entry">
						Equities analysts predict that Automatic Data Processing (NASDAQ:ADP) will post sales of $3.29 billion for the current quarter, according to Zacks. Six analysts have made estimates for Automatic Data Processing&#8217;s earnings. The...&nbsp;<a href='https://transcriptdaily.com/2020/06/29/automatic-data-processing-nasdaqadp-expected-to-post-quarterly-sales-of-3-29-billion.html'></a>					</div></a>
				</section> <!-- end archive -->
								<section class="archive">
					<a href="https://transcriptdaily.com/2020/06/29/automatic-data-processing-nasdaqadp-expected-to-post-earnings-of-0-96-per-share.html" rel="bookmark" title="Automatic Data Processing (NASDAQ:ADP) Expected to Post Earnings of $0.96 Per Share">
					<img src="https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/automatic-data-processing-logo.png&amp;h=100&amp;w=100&amp;zc=1" alt="Automatic Data Processing (NASDAQ:ADP) Expected to Post Earnings of $0.96 Per Share" />
					<h2>Automatic Data Processing (NASDAQ:ADP) Expected to Post Earnings of $0.96 Per Share</h2>
					<p class="postmeta">
						Posted by <a href="https://transcriptdaily.com/author/lasteadman" title="Posts by Lauren Steadman" rel="author">Lauren Steadman</a> on Jun 29th, 2020 // <span class="comments-link">Comments off</span>					</p><!--end .postmeta-->
					<div class="entry">
						Equities research analysts expect Automatic Data Processing (NASDAQ:ADP) to announce $0.96 earnings per share for the current quarter, Zacks Investment Research reports. Six analysts have made estimates for Automatic Data Processing&#8217;s...&nbsp;<a href='https://transcriptdaily.com/2020/06/29/automatic-data-processing-nasdaqadp-expected-to-post-earnings-of-0-96-per-share.html'></a>					</div></a>
				</section> <!-- end archive -->
								<section class="archive">
					<a href="https://transcriptdaily.com/2020/06/29/3-29-billion-in-sales-expected-for-automatic-data-processing-nasdaqadp-this-quarter.html" rel="bookmark" title="$3.29 Billion in Sales Expected for Automatic Data Processing (NASDAQ:ADP) This Quarter">
					<img src="https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/automatic-data-processing-logo.png&amp;h=100&amp;w=100&amp;zc=1" alt="$3.29 Billion in Sales Expected for Automatic Data Processing (NASDAQ:ADP) This Quarter" />
					<h2>$3.29 Billion in Sales Expected for Automatic Data Processing (NASDAQ:ADP) This Quarter</h2>
					<p class="postmeta">
						Posted by <a href="https://transcriptdaily.com/author/jocasey" title="Posts by Joseph Casey" rel="author">Joseph Casey</a> on Jun 29th, 2020 // <span class="comments-link">Comments off</span>					</p><!--end .postmeta-->
					<div class="entry">
						Brokerages expect Automatic Data Processing (NASDAQ:ADP) to post $3.29 billion in sales for the current quarter, Zacks Investment Research reports. Six analysts have provided estimates for Automatic Data Processing&#8217;s earnings....&nbsp;<a href='https://transcriptdaily.com/2020/06/29/3-29-billion-in-sales-expected-for-automatic-data-processing-nasdaqadp-this-quarter.html'></a>					</div></a>
				</section> <!-- end archive -->
								<section class="archive">
					<a href="https://transcriptdaily.com/2020/06/27/fred-alger-management-llc-sells-8000-shares-of-adaptive-biotechnologies-corporation-nasdaqadpt.html" rel="bookmark" title="Fred Alger Management LLC Sells 8,000 Shares of Adaptive Biotechnologies Corporation (NASDAQ:ADPT)">
					<img src="https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/generic-stocks.jpg&amp;h=100&amp;w=100&amp;zc=1" alt="Fred Alger Management LLC Sells 8,000 Shares of Adaptive Biotechnologies Corporation (NASDAQ:ADPT)" />
					<h2>Fred Alger Management LLC Sells 8,000 Shares of Adaptive Biotechnologies Corporation (NASDAQ:ADPT)</h2>
					<p class="postmeta">
						Posted by <a href="https://transcriptdaily.com/author/cawalker" title="Posts by Casey Walker" rel="author">Casey Walker</a> on Jun 27th, 2020 // <span class="comments-link">Comments off</span>					</p><!--end .postmeta-->
					<div class="entry">
						Fred Alger Management LLC lowered its stake in shares of  Adaptive Biotechnologies Corporation (NASDAQ:ADPT) by 28.4% in the 1st quarter, according to the company in its most recent disclosure with the SEC. The firm owned 20,171 shares...&nbsp;<a href='https://transcriptdaily.com/2020/06/27/fred-alger-management-llc-sells-8000-shares-of-adaptive-biotechnologies-corporation-nasdaqadpt.html'></a>					</div></a>
				</section> <!-- end archive -->
								<section class="archive">
					<a href="https://transcriptdaily.com/2020/06/27/183780-shares-in-adaptive-biotechnologies-corporation-nasdaqadpt-bought-by-advisor-group-holdings-inc.html" rel="bookmark" title="183,780 Shares in Adaptive Biotechnologies Corporation (NASDAQ:ADPT) Bought by Advisor Group Holdings Inc.">
					<img src="https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/generic-stocks.jpg&amp;h=100&amp;w=100&amp;zc=1" alt="183,780 Shares in Adaptive Biotechnologies Corporation (NASDAQ:ADPT) Bought by Advisor Group Holdings Inc." />
					<h2>183,780 Shares in Adaptive Biotechnologies Corporation (NASDAQ:ADPT) Bought by Advisor Group Holdings Inc.</h2>
					<p class="postmeta">
						Posted by <a href="https://transcriptdaily.com/author/lasteadman" title="Posts by Lauren Steadman" rel="author">Lauren Steadman</a> on Jun 27th, 2020 // <span class="comments-link">Comments off</span>					</p><!--end .postmeta-->
					<div class="entry">
						Advisor Group Holdings Inc. purchased a new position in shares of  Adaptive Biotechnologies Corporation (NASDAQ:ADPT) in the 1st quarter, according to the company in its most recent filing with the Securities and Exchange Commission...&nbsp;<a href='https://transcriptdaily.com/2020/06/27/183780-shares-in-adaptive-biotechnologies-corporation-nasdaqadpt-bought-by-advisor-group-holdings-inc.html'></a>					</div></a>
				</section> <!-- end archive -->
								<section class="archive">
					<a href="https://transcriptdaily.com/2020/06/26/meeder-asset-management-inc-buys-187-shares-of-automatic-data-processing-nasdaqadp.html" rel="bookmark" title="Meeder Asset Management Inc. Buys 187 Shares of Automatic Data Processing (NASDAQ:ADP)">
					<img src="https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/automatic-data-processing-logo.png&amp;h=100&amp;w=100&amp;zc=1" alt="Meeder Asset Management Inc. Buys 187 Shares of Automatic Data Processing (NASDAQ:ADP)" />
					<h2>Meeder Asset Management Inc. Buys 187 Shares of Automatic Data Processing (NASDAQ:ADP)</h2>
					<p class="postmeta">
						Posted by <a href="https://transcriptdaily.com/author/liflegge" title="Posts by Linda Flegge" rel="author">Linda Flegge</a> on Jun 26th, 2020 // <span class="comments-link">Comments off</span>					</p><!--end .postmeta-->
					<div class="entry">
						Meeder Asset Management Inc. lifted its stake in shares of  Automatic Data Processing (NASDAQ:ADP) by 17.0% in the first quarter, according to its most recent Form 13F filing with the Securities and Exchange Commission (SEC). The fund...&nbsp;<a href='https://transcriptdaily.com/2020/06/26/meeder-asset-management-inc-buys-187-shares-of-automatic-data-processing-nasdaqadp.html'></a>					</div></a>
				</section> <!-- end archive -->
								<section class="archive">
					<a href="https://transcriptdaily.com/2020/06/26/adaptive-biotechnologies-corporation-nasdaqadpt-svp-stacy-l-taylor-sells-2880-shares.html" rel="bookmark" title="Adaptive Biotechnologies Corporation (NASDAQ:ADPT) SVP Stacy L. Taylor Sells 2,880 Shares">
					<img src="https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/generic-stocks.jpg&amp;h=100&amp;w=100&amp;zc=1" alt="Adaptive Biotechnologies Corporation (NASDAQ:ADPT) SVP Stacy L. Taylor Sells 2,880 Shares" />
					<h2>Adaptive Biotechnologies Corporation (NASDAQ:ADPT) SVP Stacy L. Taylor Sells 2,880 Shares</h2>
					<p class="postmeta">
						Posted by <a href="https://transcriptdaily.com/author/cawalker" title="Posts by Casey Walker" rel="author">Casey Walker</a> on Jun 26th, 2020 // <span class="comments-link">Comments off</span>					</p><!--end .postmeta-->
					<div class="entry">
						Adaptive Biotechnologies Corporation (NASDAQ:ADPT) SVP Stacy L. Taylor sold 2,880 shares of the stock in a transaction on Wednesday, June 24th. The stock was sold at an average price of $46.68, for a total transaction of $134,438.40....&nbsp;<a href='https://transcriptdaily.com/2020/06/26/adaptive-biotechnologies-corporation-nasdaqadpt-svp-stacy-l-taylor-sells-2880-shares.html'></a>					</div></a>
				</section> <!-- end archive -->
				
				<div class="navigation" style="margin-bottom:10px;">
					<a href="https://transcriptdaily.com/page/2?s=ADP" >Next &raquo;</a>				</div><!--end .navigation-->

			<div class="bottom-square-ad">
				<script type="text/javascript">
				(function() {
				var html = "javascript:\"<body style='margin: 0;'><script src='https://www.googletagservices.com/tag/js/gpt.js'>googletag.pubads().set('page_url','"+window.location.href+"').definePassback('/8095840/342.network-acn.com_desktop_300x250', [300, 250]).display();<\/script></body>\"";
				document.write('<iframe width="300" height="250" frameBorder="0" scrolling="no" marginheight="0" marginwidth="0" src="'+encodeURI(html)+'"></iframe>');
				})();
				</script>
			</div> <!-- end first .bottom-square-ad -->

			<div class="bottom-square-ad">
				<script type="text/javascript">
				(function() {
				var html = "javascript:\"<body style='margin: 0;'><script src='https://www.googletagservices.com/tag/js/gpt.js'>googletag.pubads().set('page_url','"+window.location.href+"').definePassback('/8095840/342.network-acn.com_desktop_300x250', [300, 250]).display();<\/script></body>\"";
				document.write('<iframe width="300" height="250" frameBorder="0" scrolling="no" marginheight="0" marginwidth="0" src="'+encodeURI(html)+'"></iframe>');
				})();
				</script>
			</div> <!-- end second .bottom-square-ad -->

		</main> <!-- end main -->
	<aside>
	<iframe src="https://marketbeat.com/scripts/MoreOnMarketBeat.aspx" width="336" height="600" frameborder="no"></iframe><br><br>
	
	
<!-- first square unit -->

<div class="ad336x280">
<!-- Network Wide AdSense Unit - Top Sidebar Position -->
<ins class="adsbygoogle" style="display:block" data-ad-client="ca-pub-9373162611283935" data-ad-slot="1875628183" data-ad-format="auto" data-full-width-responsive="true"></ins>
<script>(adsbygoogle = window.adsbygoogle || []).push({});</script>
<!-- End AdSense Unit -->
</div>

<!-- end first square unit -->

<!-- second square unit -->
<div class="ad336x280">
<!-- Network Wide AdSense Unit - Middle Sidebar Position -->
<ins class="adsbygoogle" style="display:block" data-ad-client="ca-pub-9373162611283935" data-ad-slot="9445683366" data-ad-format="auto" data-full-width-responsive="true"></ins>
<script>(adsbygoogle = window.adsbygoogle || []).push({});</script>
<!-- End AdSense Unit -->
</div>

<!-- end second square unit -->


<!-- OptIn Form -->

<!-- Start Sidebar Registration -->
    <div class="sidebar-email">
                        <h3>Free Email Newsletter</h3>
         	Complete the form below to receive the latest headlines and analysts' recommendations for your stocks with our free daily email newsletter:<br/>
        <form method="get" action="https://www.marketbeat.com/newsletter/default.aspx">
        <input id="RegisterEmailSidebar" name="RegisterEmail" type="email" placeholder="Your Email Address">
        <input type="hidden" id="Hidden1" name="RegistrationCode" value="Transcript Daily-Sidebar">
        <input type="hidden" id="Hidden2" name="RegisterTicker" value="NASDAQ:ADP" />        <input type="submit" name="submit" onclick="return CheckEmail('RegisterEmailSidebar', 'ShowSuggestionSidebar');" value="Subscribe Now (Free Sign-Up)" class="button" style="width:336px;height:30px">
    <div id="ShowSuggestionSidebar" style="padding-top:7px"></div>
    </form>
    </div>

<!-- End Sidebar Registration -->

<div>
<a class="twitter-follow-button"
  href="https://twitter.com/TranscriptDaily"
  data-size="large">
Follow @TranscriptDaily</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
</div>

<!-- Start IMS -->
<div id="TranscriptDaily_ROS_RightRail_1" class="text-center">
			<script type="text/javascript">
			apntag.anq.push(function() {
				apntag.showTag('TranscriptDaily_ROS_RightRail_1');
			});
			</script>
		</div>
<!-- End IMS --> 


<!-- start Recent Posts -->
        <br/>
        <div>
        <h3>Recent Posts</h3>
            <ul>
                        <li class="recent-posts"><a href="https://transcriptdaily.com/2020/07/26/ishares-north-american-tech-software-etf-batsigv-shares-bought-by-focused-wealth-management-inc.html">iShares North American Tech-Software ETF (BATS:IGV) Shares Bought by Focused Wealth Management Inc</a></li>
                        <li class="recent-posts"><a href="https://transcriptdaily.com/2020/07/26/stonebridge-financial-planning-group-llc-cuts-stake-in-invesco-dynamic-leisure-and-entertainment-etf-nysearcapej.html">Stonebridge Financial Planning Group LLC Cuts Stake in Invesco Dynamic Leisure and Entertainment ETF (NYSEARCA:PEJ)</a></li>
                        <li class="recent-posts"><a href="https://transcriptdaily.com/2020/07/26/stonebridge-financial-planning-group-llc-buys-250-shares-of-target-co-nysetgt.html">Stonebridge Financial Planning Group LLC Buys 250 Shares of Target Co. (NYSE:TGT)</a></li>
                        <li class="recent-posts"><a href="https://transcriptdaily.com/2020/07/26/stonebridge-financial-planning-group-llc-has-30000-position-in-flowserve-corp-nysefls.html">Stonebridge Financial Planning Group LLC Has $30,000 Position in Flowserve Corp (NYSE:FLS)</a></li>
                        <li class="recent-posts"><a href="https://transcriptdaily.com/2020/07/26/stonebridge-financial-planning-group-llc-has-45000-stock-position-in-invesco-sp-500-pure-value-etf-nysearcarpv.html">Stonebridge Financial Planning Group LLC Has $45,000 Stock Position in Invesco S&#038;P 500 Pure Value ETF (NYSEARCA:RPV)</a></li>
                        <li class="recent-posts"><a href="https://transcriptdaily.com/2020/07/26/cubic-asset-management-llc-has-8-11-million-stock-position-in-alphabet-inc-nasdaqgoog.html">Cubic Asset Management LLC Has $8.11 Million Stock Position in Alphabet Inc (NASDAQ:GOOG)</a></li>
                        <li class="recent-posts"><a href="https://transcriptdaily.com/2020/07/26/tabula-rasa-healthcare-inc-nasdaqtrhc-shares-sold-by-nn-investment-partners-holdings-n-v.html">Tabula Rasa HealthCare Inc (NASDAQ:TRHC) Shares Sold by NN Investment Partners Holdings N.V.</a></li>
                        <li class="recent-posts"><a href="https://transcriptdaily.com/2020/07/26/nn-investment-partners-holdings-n-v-raises-stock-holdings-in-cvs-health-corp-nysecvs.html">NN Investment Partners Holdings N.V. Raises Stock Holdings in CVS Health Corp (NYSE:CVS)</a></li>
                        <li class="recent-posts"><a href="https://transcriptdaily.com/2020/07/26/nn-investment-partners-holdings-n-v-has-14-65-million-holdings-in-atmos-energy-co-nyseato.html">NN Investment Partners Holdings N.V. Has $14.65 Million Holdings in Atmos Energy Co. (NYSE:ATO)</a></li>
                        <li class="recent-posts"><a href="https://transcriptdaily.com/2020/07/26/nn-investment-partners-holdings-n-v-makes-new-investment-in-extra-space-storage-inc-nyseexr.html">NN Investment Partners Holdings N.V. Makes New Investment in Extra Space Storage, Inc. (NYSE:EXR)</a></li>
                        <li class="recent-posts"><a href="https://transcriptdaily.com/2020/07/26/nn-investment-partners-holdings-n-v-acquires-14497-shares-of-clorox-co-nyseclx.html">NN Investment Partners Holdings N.V. Acquires 14,497 Shares of Clorox Co (NYSE:CLX)</a></li>
                        <li class="recent-posts"><a href="https://transcriptdaily.com/2020/07/26/nn-investment-partners-holdings-n-v-has-16-51-million-holdings-in-honeywell-international-inc-nysehon.html">NN Investment Partners Holdings N.V. Has $16.51 Million Holdings in Honeywell International Inc. (NYSE:HON)</a></li>
                        <li class="recent-posts"><a href="https://transcriptdaily.com/2020/07/26/wp-carey-inc-nysewpc-shares-bought-by-nn-investment-partners-holdings-n-v.html">WP Carey Inc (NYSE:WPC) Shares Bought by NN Investment Partners Holdings N.V.</a></li>
                        <li class="recent-posts"><a href="https://transcriptdaily.com/2020/07/26/nn-investment-partners-holdings-n-v-decreases-position-in-alphabet-inc-nasdaqgoog.html">NN Investment Partners Holdings N.V. Decreases Position in Alphabet Inc (NASDAQ:GOOG)</a></li>
                        <li class="recent-posts"><a href="https://transcriptdaily.com/2020/07/26/nn-investment-partners-holdings-n-v-has-21-70-million-stock-holdings-in-3m-co-nysemmm.html">NN Investment Partners Holdings N.V. Has $21.70 Million Stock Holdings in 3M Co (NYSE:MMM)</a></li>
                        <li class="recent-posts"><a href="https://transcriptdaily.com/2020/07/26/salesforce-com-inc-nysecrm-shares-acquired-by-nn-investment-partners-holdings-n-v.html">salesforce.com, inc. (NYSE:CRM) Shares Acquired by NN Investment Partners Holdings N.V.</a></li>
                        <li class="recent-posts"><a href="https://transcriptdaily.com/2020/07/26/nn-investment-partners-holdings-n-v-has-22-41-million-holdings-in-roper-technologies-inc-nyserop.html">NN Investment Partners Holdings N.V. Has $22.41 Million Holdings in Roper Technologies Inc (NYSE:ROP)</a></li>
                        <li class="recent-posts"><a href="https://transcriptdaily.com/2020/07/26/dxc-technology-co-nysedxc-shares-acquired-by-heritage-investors-management-corp.html">DXC Technology Co (NYSE:DXC) Shares Acquired by Heritage Investors Management Corp</a></li>
                        <li class="recent-posts"><a href="https://transcriptdaily.com/2020/07/26/heritage-investors-management-corp-boosts-stock-holdings-in-cvs-health-corp-nysecvs.html">Heritage Investors Management Corp Boosts Stock Holdings in CVS Health Corp (NYSE:CVS)</a></li>
                        <li class="recent-posts"><a href="https://transcriptdaily.com/2020/07/26/csx-co-nasdaqcsx-shares-bought-by-nn-investment-partners-holdings-n-v.html">CSX Co. (NASDAQ:CSX) Shares Bought by NN Investment Partners Holdings N.V.</a></li>
                        </ul>
        </div>  

<!-- end recent posts -->
</aside><!--end #sidebar-->
<div style="clear: both;"></div>
	</div> <!-- end .width-limiter -->
<footer class="full-width">
			<div class="width-limiter">
				<div id="footer-info" class="add-padding">
					<nav class="navigation"><ul id="menu-categories-for-menus-1" class="menu"><li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-79"><a href="https://transcriptdaily.com/headlines">Headlines</a></li>
<li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-75"><a href="https://transcriptdaily.com/business">Business</a></li>
<li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-77"><a href="https://transcriptdaily.com/markets">Markets</a></li>
<li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-80"><a href="https://transcriptdaily.com/politics">Politics</a></li>
<li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-78"><a href="https://transcriptdaily.com/technology">Technology</a></li>
<li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-76"><a href="https://transcriptdaily.com/health">Health</a></li>
</ul></nav>					<span id="copyright">
						&copy; 2006-2020 <a href="https://transcriptdaily.com">Transcript Daily</a>
					</span>
				</div><!-- end #footer-info -->
			</div>	
		</footer>
		<script type='text/javascript' src='https://transcriptdaily.com/wp-includes/js/wp-embed.min.js?ver=5.4.2'></script>

<!-- MarketBeat News Network StatCounter Code -->
<script type="text/javascript">var sc_project=9021069; var sc_invisible=1; var sc_security="fdde5482"; var sc_https=1; </script>
<script type="text/javascript" src="https://www.statcounter.com/counter/counter.js"></script>
<noscript><img class="statcounter" src="https://c.statcounter.com/9021069/0/fdde5482/1/" height="1" width="1"></noscript>
<!-- End MarketBeat News Network StatCounter Code -->

<!-- Start of StatCounter Code for Transcript Daily -->
<script type="text/javascript">
var sc_project=11301659; 
var sc_invisible=1; 
var sc_security="a399788a"; 
var sc_https=1; 
var scJsHost = (("https:" == document.location.protocol) ? "https://secure." : "http://www.");
</script>
<script type="text/javascript" src="https://www.statcounter.com/counter/counter.js"></script><noscript><img class="statcounter" src="//c.statcounter.com/11301659/0/a399788a/1/" alt="Web Analytics"></a></noscript>
<!-- End of StatCounter Code for Transcript Daily -->
	

<!-- Begin Social Sharing -->
	<!-- End Social Sharing -->

<!-- Begin Internal Tracking Pixel 2 -->
<script type='text/javascript'>document.write('<img src="https://www.american' + 'consumernews.net/scripts/viewcount.ashx?ArticleHistoryID=57857590&PostDate=2020-7-26&type=f&id=7547600&domain=transcriptdaily.com&referrer=' + encodeURIComponent(document.referrer) + '" />');</script>
<!-- End Internal Tracking Pixel 2-->

<!-- Begin comScore Tag -->
<script>
  var _comscore = _comscore || [];
  _comscore.push({ c1: "2", c2: "16807273" });
  (function() {
    var s = document.createElement("script"), el = document.getElementsByTagName("script")[0]; s.async = true;
    s.src = (document.location.protocol == "https:" ? "https://sb" : "http://b") + ".scorecardresearch.com/beacon.js";
    el.parentNode.insertBefore(s, el);
  })();
</script>
<noscript>
  <img src="http://b.scorecardresearch.com/p?c1=2&c2=16807273&cv=2.0&cj=1" />
</noscript>
<!-- End comScore Tag -->



</div>



	</body>
</html>